---
# tasks file for common

- name: Upgrade all
  apt:
    upgrade: dist
    update_cache: yes
  register: result
  until: result is not failed
  retries: 5
  delay: 5

- name: Install list of packages - pip
  apt:
    name : openjdk-8-jdk
    state: latest
