---
# Concourse tasks file

# Fetch docker compose file for Concourse Dev
- name: Download Concourse Dev 
  get_url:
    url: "https://concourse-ci.org/docker-compose.yml"
    dest: "/tmp"

- name: Run `docker-compose up` again
  docker_compose:
    project_src: ./
    build: no
  register: output

- debug:
    var: output

- meta: end_play
