---
# Docker tasks file for Concourse
#- name: Install list of packages
#  #dnf:
#  package:
#    name: "{{ item }}"
#    state: present
#  with_items: "{{ packages }}"

#- name: Install pip libraries
#  become: no
#  pip:
#    name: "{{ pip_libraries }}"
#    #executable: pip3
#    extra_args: "--user"
#    state: latest

- name: Install Docker Engine
  shell: "amazon-linux-extras install -y {{ item }}"
  with_items: "{{ docker_packages }}"

- name: Make sure Docker service is running
  service:
    enabled: yes
    name: docker
    state: started

- name: Add ec2-user to docker group
  user:
    append: yes
    name: ec2-user
    group: docker

# Reset SSH connection
- name: Reset ssh connection to allow user changes to affect 'current login user' (apply docker group membership to current shell)
  meta: reset_connection
