---
# tasks file for Concourse
- name: Enable repo(s)
  shell: "amazon-linux-extras install -y {{ item }}"
  with_items: "{{ amzn2_repos }}"

- name: Uninstall Old Versions
  package:
    name: "{{ item }}"
    state: absent
  with_items: "{{ uninstall_packages }}"

- name: Configure & deploy docker
  include: docker.yml

- name: Deploy Conourse
  include: concourse.yml
  when: role is defined

- fail: msg="Quitting. This playbook requires Concourse Role to be set!"
  when: role is undefined
