---
# tasks file for drone
- name: Enable repo(s)
  shell: "amazon-linux-extras install -y {{ item }}"
  with_items: "{{ amzn2_repos }}"

- name: Install list of packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"

- name: Install pip libraries
  pip:
    name: "{{ pip_libraries }}"
    extra_args: "--user"
    state: latest

- name: Configure & deploy docker
  include: docker.yml

- name: Deploy Conourse
  include: concourse.yml
  when: role is defined

- fail: msg="Quitting. This playbook requires Concourse Role to be set!"
  when: role is undefined
