---
# Concourse system pre-reqs tasks file
# reqiured modules
- name: Add the BTRFS module
  modprobe:
    name: btrfs
    state: present

# sysctl entries
- sysctl:
    name: vm.swappiness
    value: '0'
    state: present
    sysctl_file: /etc/sysctl.d/99-sysctl.conf

- sysctl:
    name: vm.vfs_cache_pressure
    value: '200'
    state: present
    sysctl_file: /etc/sysctl.d/99-sysctl.conf
