---
# defaults file for concourse
amzn2_repos:
- epel

dirs:
- /etc/concourse.d/{{ role }}
- "{{ KEYS_DIRECTORY }}"
- /etc/concourse.d/pipelines

pip_libraries:
- awscli
- botocore
- boto3
- docker
#- docker-compose

s3_downloads:
- docker-compose/{{ role }}
- pipelines/cdp-ecs-pipeline.yaml
- pipelines/cdp-k8s-pipeline.yaml
- pipelines/variables.yaml
- pipelines/zax-test-pipeline.yaml

uninstall_packages:
- docker
- docker-client
- docker-client-latest
- docker-common
- docker-latest
- docker-latest-logrotate
- docker-logrotate
- docker-engine

packages:
- ca-certificates
- gcc
- openssl
#- openvpn
- python3
- tree

docker_packages:
- docker="{{ docker_version }}"
