---
# defaults file for drone
amzn2_repos:
- epel

pip_libraries:
- botocore
- boto3

uninstall_packages:
- docker
- docker-client
- docker-client-latest
- docker-common
- docker-latest
- docker-latest-logrotate
- docker-logrotate
- docker-engine

packages:
- ca-certificates
- openssl
- openvpn

docker_packages:
- docker="{{ docker_version }}"
