version: '3'

services:
  drone:
    image: drone/drone:1
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
    command: quickstart
    privileged: true
    ports: ["80:80"]
    environment:
      DRONE_AGENTS_ENABLED: "true"
      DRONE_BITBUCKET_CLIENT_ID: kWd4tpuR8hevG8mCSb
      DRONE_BITBUCKET_CLIENT_SECRET: 7fVRmrfU2vFRPzP4BEyAR8crXkCyGsQQ
      DRONE_RPC_SECRET: {{ DRONE_RPC_SECRET }}
      DRONE_SERVER_HOST: "drone.stratotech.co.uk"
      DRONE_SERVER_PROTO: "http"
      DRONE_USER_CREATE: username:dev,admin:true
      DRONE_LOGS_DEBUG: "true"
      DRONE_LOGS_TEXT: "true"
      DRONE_LOGS_PRETTY: "true"
      DRONE_LOGS_COLOR: "true"

  drone-runner:
    image: drone/drone-runner-docker:1
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
    command: quickstart
    privileged: true
    ports: ["3000:3000"]
    environment:
      DRONE_RPC_PROTO: "http"
      DRONE_RPC_HOST: "drone.stratotech.co.uk"
      DRONE_RPC_SECRET: {{ DRONE_RPC_SECRET }}
      DRONE_RUNNER_CAPACITY: 2
      DRONE_RUNNER_NAME: drone_runner
      DRONE_LOGS_DEBUG: "true"
      DRONE_LOGS_TEXT: "true"
      DRONE_LOGS_PRETTY: "true"
      DRONE_LOGS_COLOR: "true"
